#ifndef DOWNLOADSONG_H
#define DOWNLOADSONG_H

#define CLIENT_DOWNLOAD_PORT 6678

DWORD WINAPI beginDownload(LPVOID);
int download();
void CALLBACK downloadReadRoutine(DWORD, DWORD, LPWSAOVERLAPPED, DWORD);

#endif // DOWNLOADSONG_H
